matrix:
    include:
      - language: swift
        osx_image: xcode12.2
        xcode_project: ClientApp.xcodeproj # path to your xcodeproj folder
        xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone X
        # script: xcodebuild -project ClientApp.xcodeproj -target ClientApp -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
      - language: python
        python: 3.7
        before_install:
          - cd Server/
        install:
          - pip install -r requirements.txt
        script:
          - python main.py -t true
