matrix:
    include:
      - language: swift
        osx_image: xcode11
        script: xcodebuild -project ClientApp.xcodeproj -target ClientApp -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
      - language: python
        python: 3.7
        before_install:
          - cd Server/
        install:
          - pip install -r requirements.txt
        script:
          - python main.py
